#!/bin/bash

# loop until the VM starts responding to pings
while ! erl_call_rpc 'erlang is_alive' > /dev/null
do
    sleep 1
done

# loop until the name provided as argument gets
# registered
while true
do
    if [ "$(erl_call_eval "whereis($1).")" != "undefined" ]
    then
        break
    fi
done
